### ISSUE TITLE
how to use salt?

### ISSUE THREAD

**Issue by NewITCorp** [olexale/hashids#3]
Hi,  how do I use salt to decrypt?

in https://hashids.org/dart/
final hashids = HashIds('this is my salt');

in this github
final hashids = HashIds();

thanks

**Comment by olexale** [comment]
Hey,

Sorry, I just noticed this ticket. You may use it like this:
```dart
final hashids = HashIds(
    salt: 'this is my salt',
  );
```

Kind regards,
Oleksandr
