### ISSUE TITLE
Decode function overloading

### ISSUE THREAD

**Issue by NewITCorp** [olexale/hashids#4]
Hi, there are missing decode function variations

final hashids = HashIds();
final number = hashids.decode(fromNumber); // not found in hashids2.dart
final list = hashids.decode(fromList); 
final string = hashids.decode(fromString); // // not found in hashids2.dart

how do I use decode function returning string?
thanks

**Comment by olexale** [comment]
Hey,

Function overloading is not supported in Dart, so the package can not support this behavior.

Kind regards,
Oleksandr
